version: '3.8'
services:
  unit:
    platform: ${PLATFORM:-linux/amd64}
    build: .
    volumes:
      - .:/app
      - ./config/unit:/docker-entrypoint.d
    environment:
      APP_ENV: ${APP_ENV:-dev}
    ports:
      - "8080:8080"
